sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge SEMGroup14
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network SEMGroup14 mongo
  - docker build -t SEMGroup14
  - docker run --network SEMGroup14 SEMGroup14
